// Données des artisans partenaires, page "Nos Artisans" (/univers/nos-artisans)

export const CATEGORIES = [
  { key: 'boulangerie', label: 'Boulangerie', icon: 'wheat' },
  { key: 'patisserie', label: 'Pâtisserie', icon: 'cake' },
  { key: 'boissons', label: 'Boissons', icon: 'bottle' },
  { key: 'laitier', label: 'Autres', icon: 'leaf' },
]

export const ARTISANS = [
  {
    slug: 'maison-marques',
    nom: 'Maison Marques',
    ville: 'Asnières-sur-Seine',
    categorie: 'boulangerie',
    categorieLabel: 'Boulangerie & Viennoiseries',
    specialite: 'Viennoiseries',
    eyebrow: "Viennoiseries d'exception",
    description: "On travaille avec Maison Marques depuis le début. Référencée Gault & Millau, leurs viennoiseries sont confectionnées chaque matin avec des farines françaises rigoureusement sélectionnées. C'est le genre de partenaire qui ne déçoit jamais, régulier, précis, toujours bon.",
    tags: ['Gault & Millau', 'Fabrication quotidienne', 'Île-de-France'],
    img: '/maison-marques.avif',
    avatar: '/carlos-marques.avif',
    map: { x: 47, y: 24 },
    creationsHref: '/creations/petits-dejeuners-et-pauses',
    creationsLabel: 'Petits-déjeuners & Pauses',
    creations: [
      { id: 'viennoiseries-duo', nom: 'Plateau duo de viennoiseries', img: '/prod-viennoiseries.webp', href: '/creations/petits-dejeuners-et-pauses/viennoiseries-duo' },
      { id: 'viennoiseries-melangees', nom: 'Plateau de viennoiseries', img: '/prod-viennoiseries.webp', href: '/creations/petits-dejeuners-et-pauses/viennoiseries-melangees' },
      { id: 'chouquettes', nom: 'Plateau de chouquettes', img: '/prod-chouquettes.webp', href: '/creations/petits-dejeuners-et-pauses/chouquettes' },
    ],
  },
  {
    slug: 'un-passage-a-lautre',
    nom: "D'un Passage à l'Autre",
    ville: 'Boulogne-Billancourt',
    categorie: 'boulangerie',
    categorieLabel: 'Boulangerie & Viennoiseries',
    specialite: 'Boulangerie · Cakes & Crêpes',
    eyebrow: 'Boulangerie artisanale',
    description: "Une boulangerie artisanale boulonnaise que peu de gens connaissent et qu'on est fiers de faire découvrir. Deux adresses rue Galliéni et rue Paul Bert à Boulogne, dont une gamme certifiée bio. Leurs cakes et crêpes apportent une vraie touche maison à nos prestations.",
    tags: ['Boulogne-Billancourt', 'Gamme bio certifiée', 'Fait maison'],
    img: '/prod-cake-marbre.webp',
    avatar: '/cake-passage-avatar.webp',
    map: { x: 38, y: 25 },
    creationsHref: '/creations/petits-dejeuners-et-pauses',
    creationsLabel: 'Petits-déjeuners & Pauses',
    creations: [
      { id: 'cake-marbre', nom: 'Cake marbré maison', img: '/prod-cake-marbre.webp', href: '/creations/petits-dejeuners-et-pauses/cake-marbre' },
      { id: 'crepes', nom: 'Crêpe maison', img: '/prod-crepes.webp', href: '/creations/petits-dejeuners-et-pauses/crepes' },
    ],
  },
  {
    slug: 'mado-paris',
    nom: 'Mado Paris',
    ville: 'Paris',
    categorie: 'patisserie',
    categorieLabel: 'Pâtisserie',
    specialite: 'Madeleines',
    eyebrow: 'Madeleines artisanales',
    description: "Les madeleines Mado Paris sont notre produit signature. Fabriquées dans leur atelier parisien avec des ingrédients biologiques français, sans huile de palme. Moelleuses, dorées, reconnaissables au premier goût : nos clients les reconnaissent avant même de lire l'étiquette.",
    tags: ['Ingrédients biologiques', 'Sans huile de palme', 'Paris'],
    img: '/madeleine-home.webp',
    map: { x: 53, y: 19 },
    creationsHref: '/creations/petits-dejeuners-et-pauses',
    creationsLabel: 'Coffrets de madeleines',
    creations: [
      { id: 'madeleines-10', nom: 'Coffret de madeleines · 10', img: '/prod-madeleines-10.webp', href: '/creations/petits-dejeuners-et-pauses/madeleines-10' },
      { id: 'madeleines-20', nom: 'Coffret de madeleines · 20', img: '/prod-madeleines-20.webp', href: '/creations/petits-dejeuners-et-pauses/madeleines-20' },
      { id: 'madeleines-50', nom: 'Coffret de madeleines · 50', img: '/prod-madeleines-50.webp', href: '/creations/petits-dejeuners-et-pauses/madeleines-50' },
    ],
  },
  {
    slug: 'laura-todd',
    nom: 'Laura Todd',
    ville: 'Paris',
    categorie: 'patisserie',
    categorieLabel: 'Pâtisserie',
    specialite: 'Cookies',
    eyebrow: 'Cookies signature',
    description: "Installés à Paris depuis 1985, pionniers du cookie en France. Leur recette, primée à Chicago en 1933, est produite chaque jour dans leur atelier du 18e. Les cookies Laura Todd disparaissent toujours en premier sur nos plateaux. Une adresse qu'on garde précieusement.",
    tags: ['Paris depuis 1985', 'Recette signature', 'Production quotidienne'],
    img: '/laura-todd.webp',
    map: { x: 47, y: 16 },
    creationsHref: '/creations/petits-dejeuners-et-pauses',
    creationsLabel: 'Petits-déjeuners & Pauses',
    creations: [
      { id: 'cookies', nom: 'Cookie', img: '/prod-cookies.webp', href: '/creations/petits-dejeuners-et-pauses/cookies' },
    ],
  },
  {
    slug: 'pierre-morel',
    nom: 'Pierre Morel',
    ville: 'La Gacilly',
    categorie: 'patisserie',
    categorieLabel: 'Pâtisserie',
    specialite: 'Macarons',
    eyebrow: 'Macarons de précision',
    description: "Formé auprès d'un Meilleur Ouvrier de France, Pierre Morel fabrique ses macarons depuis 2013 selon une technique exigeante. Meringue italienne signature, zéro arôme artificiel, ganaches au chocolat pur origine 64%. Des macarons d'une précision et d'une régularité rarissimes.",
    tags: ['Meringue italienne', 'Formé par un MOF', 'Chocolat pur origine'],
    img: '/pm-pierre-morel.webp',
    avatar: '/pierre-morel.jpg',
    map: { x: 17, y: 36 },
    creationsHref: '/creations/petits-dejeuners-et-pauses',
    creationsLabel: 'Petits-déjeuners & Pauses',
    creations: [
      { id: 'macarons', nom: 'Macaron', img: '/prod-macarons.webp', href: '/creations/petits-dejeuners-et-pauses/macarons' },
    ],
  },
  {
    slug: 'la-ferme-de-viltain',
    nom: 'La Ferme de Viltain',
    ville: 'Jouy-en-Josas',
    categorie: 'laitier',
    categorieLabel: 'Produits laitiers',
    specialite: 'Yaourts & Produits laitiers',
    eyebrow: 'Laiterie en circuit direct',
    description: "À Jouy-en-Josas, à 17 km de Paris, la Ferme de Viltain fabrique ses yaourts depuis 1954. Leur troupeau de 350 vaches fournit le lait que leur laiterie transforme directement : yaourts natures, aux fruits, de dessert. Un circuit en direct qui se sent dans l'onctuosité : pas de transport long, pas d'intermédiaire, un produit frais qui arrive dans nos plateaux petit-déjeuner le lendemain matin.",
    tags: ['Jouy-en-Josas · 17 km de Paris', 'Depuis 1954 · 350 vaches', 'Laiterie en circuit direct'],
    img: '/ferme-viltain.webp',
    map: { x: 47, y: 34 },
    creationsHref: '/creations/pauses-gourmandes',
    creationsLabel: 'Pauses Gourmandes',
    creations: [
      { id: 'yaourt-fruits', nom: 'Yaourt Fermier', img: '/prod-yaourt-fruits.webp', href: '/creations/pauses-gourmandes/yaourt-fruits' },
    ],
  },
  {
    slug: 'alain-milliat',
    nom: 'Alain Milliat',
    ville: 'Valence',
    categorie: 'boissons',
    categorieLabel: 'Boissons',
    specialite: 'Jus & Nectars',
    eyebrow: 'Jus & nectars de fruits',
    description: "Fondée en 1997 à Valence, dans la Drôme. 38 références, fruits entiers, aucun sucre ajouté, aucun additif. La moitié des fruits vient de producteurs français. Quand on pose un jus Alain Milliat sur une table, les gens le remarquent. C'est ça, un produit qui se justifie seul.",
    tags: ['Fruits entiers', 'Sans sucre ajouté', 'Drôme · 1997'],
    img: '/selection-artisans.webp',
    map: { x: 64, y: 64 },
    creationsHref: '/creations/boissons',
    creationsLabel: 'Boissons',
    creations: [
      { id: 'jus-pomme', nom: 'Jus de Pomme', img: '/bois-jus-pomme.webp', href: '/creations/boissons/jus-pomme' },
      { id: 'jus-orange', nom: "Jus d'Orange", img: '/bois-jus-orange.webp', href: '/creations/boissons/jus-orange' },
      { id: 'jus-peche', nom: 'Nectar de Pêche', img: '/bois-jus-peche.webp', href: '/creations/boissons/jus-peche' },
    ],
  },
  {
    slug: 'les-vergers-de-plaisirs',
    nom: 'Les Vergers de Plaisirs',
    ville: 'Plaisir',
    categorie: 'boissons',
    categorieLabel: 'Boissons',
    specialite: 'Jus de pomme artisanal',
    eyebrow: 'Jus de pomme du verger',
    description: "Verger familial planté en 1982 à Plaisir, dans les Yvelines. 10 variétés de pommes sélectionnées pour le goût. Leur jus de pomme artisanal, sans aucun ajout, est l'un de nos produits les plus appréciés en pause. Local, direct, sans intermédiaire.",
    tags: ['Verger depuis 1982', 'Yvelines', 'Sans ajout'],
    img: '/verger-plaisir.avif',
    map: { x: 41, y: 31 },
    creationsHref: '/creations/boissons',
    creationsLabel: 'Boissons',
    creations: [
      { id: 'jus-pomme-verger', nom: 'Jus de Pomme du Verger', img: '/bois-jus-verger.webp', href: '/creations/boissons/jus-pomme-verger' },
    ],
  },
  {
    slug: 'mariage-freres',
    nom: 'Mariage Frères',
    ville: 'Paris',
    categorie: 'boissons',
    categorieLabel: 'Boissons',
    specialite: 'Thés & Infusions',
    eyebrow: "L'art français du thé",
    description: "Grande maison de thé française fondée en 1854. Boutique historique rue du Bourg-Tibourg, dans le Marais à Paris. Référence de l'art français du thé et pionnière des thés parfumés. Mariage Frères, c'est le choix qu'on fait quand on veut que la pause thé soit aussi soignée que le reste de la prestation.",
    tags: ['Depuis 1854', 'Le Marais', 'Grande maison'],
    img: '/mariage-freres.webp',
    avatar: '/mariage-freres-logo.jpg',
    map: { x: 53, y: 31 },
    creationsHref: '/creations/boissons',
    creationsLabel: 'Boissons',
    creations: [
      { id: 'thermos-the', nom: 'Thermos de Thé Mariage Frères', img: '/bois-thermos-cafe.webp', href: '/creations/boissons/thermos-the' },
    ],
  },
]

export function getArtisanBySlug(slug) {
  return ARTISANS.find(a => a.slug === slug)
}
