// Collections L'Écrin Traiteur, Plateaux repas

export const COLLECTIONS = [
  {
    id: 'toscane',
    nom: 'Toscane',
    emoji: '🇮🇹',
    accroche: 'Le soleil de Toscane dans votre assiette.',
    description: 'Inspirée des collines italiennes, cette collection célèbre une cuisine généreuse où les herbes fraîches, le citron confit et les produits de caractère sont à l\'honneur.',
    star: 'Poulet citron confit',
    saveurs: ['citron confit', 'basilic', 'huile d\'olive', 'herbes fraîches'],
    entree: 'Salade italienne, mozzarella, tomates confites & olives',
    plat: 'Poulet citron confit, quinoa aux légumes rôtis',
    sauce: 'Jus de volaille citronné',
    dessert: 'Panna cotta fruits rouges',
    pain: 'Pain aux céréales',
    proteines: 'volaille',
    prix: 24.90,
    bestseller: true,
    img: '/collection-toscane.webp',
    imgDetail: '/collection-toscane-detail.webp',
    couleurAccent: '#C97B5A',
  },
  {
    id: 'bistrot',
    nom: 'Bistrot',
    emoji: '🇫🇷',
    accroche: 'L\'esprit des grandes brasseries parisiennes.',
    description: 'Les classiques français revisités avec modernité. Une cuisine généreuse, franche et sans compromis, comme dans les meilleures brasseries de Paris.',
    star: 'Tataki de bœuf',
    saveurs: ['moutarde à l\'ancienne', 'ciboulette', 'sésame', 'sauce tartare'],
    entree: 'Salade de tomates anciennes & vinaigrette à l\'échalote',
    plat: 'Tataki de bœuf, riz noir au sésame',
    sauce: 'Sauce tartare maison',
    dessert: 'Mousse au chocolat grand cru',
    pain: 'Pain de campagne',
    proteines: 'viande',
    prix: 25.50,
    bestseller: false,
    img: '/creations-1.webp',
    couleurAccent: '#1E3A5F',
  },
  {
    id: 'jardin',
    nom: 'Jardin',
    emoji: '🌿',
    accroche: 'Une cuisine végétale généreuse et pleine de fraîcheur.',
    description: 'Une ode aux légumes de saison et aux céréales complètes. Colorée, équilibrée et rassasiante · la preuve qu\'une cuisine végétale peut être aussi gourmande qu\'une autre.',
    star: 'Quinoa Signature L\'Écrin',
    saveurs: ['feta', 'herbes fraîches', 'citron', 'houmous maison'],
    entree: 'Houmous maison & crudités croquantes',
    plat: 'Quinoa Signature L\'Écrin, légumes rôtis & feta',
    sauce: 'Yaourt citron & menthe',
    dessert: 'Tarte citron à la crème légère',
    pain: 'Pain aux graines',
    proteines: 'vegetarien',
    prix: 24.90,
    bestseller: false,
    img: '/buffet-garden-party.webp',
    couleurAccent: '#4A7C5F',
  },
  {
    id: 'ocean',
    nom: 'Océan',
    emoji: '🐟',
    accroche: 'Une cuisine iodée inspirée des côtes du Nord.',
    description: 'Le gravlax comme signature, les céréales comme socle, les herbes nordiques comme fil conducteur. Une collection fraîche et élégante pour les amateurs de poisson.',
    star: 'Saumon gravlax',
    saveurs: ['aneth', 'citron', 'concombre', 'crème citronnée'],
    entree: 'Tartare de concombre, aneth & crème citronnée',
    plat: 'Saumon gravlax, quinoa citronné',
    sauce: 'Crème citronnée & aneth',
    dessert: 'Fromage blanc, granola & miel',
    pain: 'Pain nordique',
    proteines: 'poisson',
    prix: 26.90,
    bestseller: false,
    img: '/creations-2.webp',
    couleurAccent: '#2C5F7A',
  },
  {
    id: 'riviera',
    nom: 'Riviera',
    emoji: '☀️',
    accroche: 'Les saveurs ensoleillées de la Méditerranée.',
    description: 'Gambas marinées, riz parfumé et légumes du soleil. Une collection généreuse et colorée qui évoque les terrasses méditerranéennes.',
    star: 'Gambas marinées',
    saveurs: ['ail', 'citron', 'herbes de Provence', 'huile d\'olive'],
    entree: 'Carpaccio de courgettes, parmesan & basilic',
    plat: 'Gambas marinées, riz parfumé aux herbes',
    sauce: 'Sauce vierge maison',
    dessert: 'Panna cotta mangue & passion',
    pain: 'Pain focaccia',
    proteines: 'poisson',
    prix: 27.90,
    bestseller: false,
    img: '/buffet-mediterraneen.webp',
    couleurAccent: '#C4A24A',
  },
  {
    id: 'provencal',
    nom: 'Provençal',
    emoji: '🍋',
    accroche: 'La Provence dans votre assiette.',
    description: 'Ratatouille froide, suprême de poulet rôti et tarte citron meringuée · une collection qui célèbre la générosité et les parfums du sud de la France.',
    star: 'Suprême de poulet rôti',
    saveurs: ['thym', 'romarin', 'citron', 'ail'],
    entree: 'Ratatouille froide & feta',
    plat: 'Suprême de poulet rôti, pommes grenailles',
    sauce: 'Jus de volaille au thym',
    dessert: 'Tarte citron meringuée',
    pain: 'Pain de campagne',
    proteines: 'volaille',
    prix: 24.90,
    bestseller: false,
    img: '/creations-3.webp',
    couleurAccent: '#C4A24A',
  },
  {
    id: 'gascogne',
    nom: 'Gascogne',
    emoji: '🦆',
    accroche: 'La générosité du Sud-Ouest dans votre plateau.',
    description: 'Magret fumé, épeautre et légumes racines · une collection qui rend hommage à la cuisine du Sud-Ouest, généreuse et profondément ancrée dans le terroir français.',
    star: 'Magret fumé',
    saveurs: ['magret', 'épeautre', 'betterave', 'vinaigre miel'],
    entree: 'Betteraves rôties, chèvre frais & noix',
    plat: 'Magret fumé, épeautre & légumes racines',
    sauce: 'Vinaigrette miel & vinaigre balsamique',
    dessert: 'Crème brûlée à la vanille',
    pain: 'Pain aux noix',
    proteines: 'viande',
    prix: 27.90,
    bestseller: false,
    img: '/buffet-sale.webp',
    couleurAccent: '#8B3A2A',
  },
  {
    id: 'boeuf-signature',
    nom: 'Périgord',
    emoji: '🥩',
    accroche: 'L\'art de cuisiner le bœuf à la française.',
    description: 'Effiloché de bœuf fondant, purée de patate douce et fondant chocolat · une collection généreuse et réconfortante inspirée de la grande tradition culinaire française.',
    star: 'Effiloché de bœuf',
    saveurs: ['bœuf confit', 'patate douce', 'épices douces', 'chocolat'],
    entree: 'Salade de lentilles vertes & vinaigrette moutarde',
    plat: 'Effiloché de bœuf, purée de patate douce',
    sauce: 'Jus réduit aux épices',
    dessert: 'Fondant chocolat noir',
    pain: 'Pain rustique',
    proteines: 'viande',
    prix: 26.90,
    bestseller: false,
    img: '/prod-brunch-gourmand.webp',
    couleurAccent: '#5C3317',
  },
  {
    id: 'mexicaine',
    nom: 'Mexicaine',
    emoji: '🌶️',
    accroche: 'Une cuisine chaleureuse et pleine de caractère.',
    description: 'Quesadilla artisanale, poulet épicé et guacamole maison · une collection festive et généreuse qui met de la bonne humeur dans vos déjeuners d\'équipe.',
    star: 'Quesadilla artisanale',
    saveurs: ['cumin', 'coriandre', 'avocat', 'lime'],
    entree: 'Maïs grillé, avocat & haricots noirs',
    plat: 'Poulet épicé, riz mexicain & guacamole maison',
    sauce: 'Guacamole & crème épicée',
    dessert: 'Brownie chocolat noir & caramel',
    pain: 'Pain tortilla',
    proteines: 'volaille',
    prix: 25.90,
    bestseller: false,
    img: '/cocktail-dejeunatoire.webp',
    couleurAccent: '#C0392B',
  },
  {
    id: 'beyrouth',
    nom: 'Beyrouth',
    emoji: '🇱🇧',
    accroche: 'Les parfums du Levant revisités par notre Chef.',
    description: 'Labneh, zaatar et poulet mariné aux épices douces · une collection chaleureuse et parfumée qui invite au voyage à travers la cuisine du Proche-Orient.',
    star: 'Poulet zaatar',
    saveurs: ['zaatar', 'tahini', 'citron', 'sésame'],
    entree: 'Labneh, zaatar & pita grillée',
    plat: 'Poulet mariné au zaatar, quinoa Signature L\'Écrin',
    sauce: 'Sauce tahini au citron & sésame',
    dessert: 'Baklava revisité & miel de fleurs',
    pain: 'Pain pita artisanal',
    proteines: 'volaille',
    prix: 25.90,
    bestseller: false,
    img: '/grand-buffet-signature.webp',
    couleurAccent: '#C07B3A',
  },
  {
    id: 'mediterrane',
    nom: 'Méditerranée',
    emoji: '🌊',
    accroche: 'La cuisine grecque dans toute sa générosité.',
    description: 'Salade grecque revisitée, saumon grillé et tiramisu pistache · une collection fraîche et colorée qui célèbre les saveurs du bassin méditerranéen.',
    star: 'Saumon grillé',
    saveurs: ['olives Kalamata', 'feta', 'citron', 'origan'],
    entree: 'Salade grecque, feta, olives Kalamata, concombre & tomates',
    plat: 'Saumon grillé, boulgour aux herbes',
    sauce: 'Huile d\'olive & herbes fraîches',
    dessert: 'Tiramisu pistache',
    pain: 'Pain blanc artisanal',
    proteines: 'poisson',
    prix: 25.90,
    bestseller: false,
    img: '/creations-featured.webp',
    couleurAccent: '#2471A3',
  },
  {
    id: 'bali',
    nom: 'Bali',
    emoji: '🥥',
    accroche: 'Un voyage gustatif au cœur de l\'Asie du Sud-Est.',
    description: 'Curry de légumes, riz coco et perles de coco · une collection végétale et exotique qui transporte vos équipes loin des repas ordinaires.',
    star: 'Curry de légumes & riz coco',
    saveurs: ['lait de coco', 'citronelle', 'gingembre', 'coriandre'],
    entree: 'Salade mangue, concombre & coriandre',
    plat: 'Curry de légumes, riz coco',
    sauce: 'Lait de coco & citron vert',
    dessert: 'Riz au lait coco & mangue',
    pain: 'Pain naan',
    proteines: 'vegan',
    prix: 24.90,
    bestseller: false,
    img: '/buffet-garden-party.webp',
    couleurAccent: '#2E7D4F',
  },
]

export const FILTRES = [
  { key: 'tous', label: 'Tous' },
  { key: 'volaille', label: 'Volaille' },
  { key: 'viande', label: 'Viande' },
  { key: 'poisson', label: 'Poisson' },
  { key: 'vegetarien', label: 'Végétarien' },
  { key: 'vegan', label: 'Végane' },
]
