// Données structurées des produits commandables (Petits-Déjeuners & Pauses uniquement)

export const PRODUCTS = [
  // Viennoiseries
  {
    id: 'viennoiseries-duo',
    name: 'Plateau duo de viennoiseries',
    shortName: 'Duo de viennoiseries',
    price: 26.80,
    label: '16 pièces — 26,80€',
    description: '16 pièces — Croissants & pains au chocolat',
    qty: '16 pièces',
    category: 'viennoiseries',
    img: '/creations-1.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'chouquettes',
    name: 'Plateau de chouquettes',
    shortName: 'Chouquettes',
    price: 26.80,
    label: '30 pièces — 26,80€',
    description: '30 pièces',
    qty: '30 pièces',
    category: 'viennoiseries',
    img: '/creations-2.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'viennoiseries-melangees',
    name: 'Plateau de viennoiseries mélangées',
    shortName: 'Viennoiseries mélangées',
    price: 48.90,
    label: '30 pièces — 48,90€',
    description: '30 pièces — Assortiment varié',
    qty: '30 pièces',
    category: 'viennoiseries',
    img: '/creations-featured.webp',
    dietary: ['Végétarien'],
  },

  // Madeleines
  {
    id: 'madeleines-10',
    name: 'Coffret de madeleines',
    shortName: 'Madeleines × 10',
    price: 24.90,
    label: '10 madeleines — 24,90€',
    description: '10 madeleines Mado Paris',
    qty: '10 pièces',
    category: 'patisserie',
    img: '/creations-3.png',
    dietary: ['Bio', 'Sans huile de palme', 'Végétarien'],
  },
  {
    id: 'madeleines-20',
    name: 'Coffret de madeleines',
    shortName: 'Madeleines × 20',
    price: 49.00,
    label: '20 madeleines — 49,00€',
    description: '20 madeleines Mado Paris',
    qty: '20 pièces',
    category: 'patisserie',
    img: '/creations-4.png',
    dietary: ['Bio', 'Sans huile de palme', 'Végétarien'],
  },
  {
    id: 'madeleines-50',
    name: 'Coffret de madeleines',
    shortName: 'Madeleines × 50',
    price: 119.00,
    label: '50 madeleines — 119,00€',
    description: '50 madeleines Mado Paris',
    qty: '50 pièces',
    category: 'patisserie',
    img: '/creations-1.png',
    dietary: ['Bio', 'Sans huile de palme', 'Végétarien'],
  },

  // Cakes
  {
    id: 'cake-marbre',
    name: 'Cake marbré maison',
    shortName: 'Cake marbré',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-2.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'cake-poire',
    name: 'Cake poire maison',
    shortName: 'Cake poire',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-featured.webp',
    dietary: ['Végétarien'],
  },
  {
    id: 'cake-framboise',
    name: 'Cake framboise',
    shortName: 'Cake framboise',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-3.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'cake-chocolat',
    name: 'Cake pépites de chocolat',
    shortName: 'Cake chocolat',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-4.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'cake-pistache',
    name: 'Cake pistache maison',
    shortName: 'Cake pistache',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-1.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'cake-citron',
    name: 'Cake citron maison',
    shortName: 'Cake citron',
    price: 12.90,
    label: '5/6 pers — 12,90€',
    description: '5/6 personnes',
    qty: '5/6 pers',
    category: 'patisserie',
    img: '/creations-2.png',
    dietary: ['Végétarien'],
  },

  // Sucrés / salés
  {
    id: 'crepes',
    name: 'Crêpe maison',
    shortName: 'Crêpes maison',
    price: 58.90,
    label: '20 grandes crêpes — 58,90€',
    description: '20 grandes crêpes',
    qty: '20 pièces',
    category: 'sucre-sale',
    img: '/creations-featured.webp',
    dietary: ['Végétarien'],
  },
  {
    id: 'brochettes-fruits',
    name: 'Brochettes de fruits',
    shortName: 'Brochettes de fruits',
    price: 48.90,
    label: '20 brochettes — 48,90€',
    description: '20 brochettes',
    qty: '20 pièces',
    category: 'sucre-sale',
    img: '/creations-3.png',
    dietary: ['Vegan', 'Sans gluten'],
  },
  {
    id: 'navettes-salees',
    name: 'Mini navettes salées',
    shortName: 'Navettes salées',
    price: 63.90,
    label: '20 navettes — 63,90€',
    description: '20 pièces',
    qty: '20 pièces',
    category: 'sucre-sale',
    img: '/creations-4.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'macarons',
    name: 'Macaron',
    shortName: 'Macarons',
    price: 64.00,
    label: '24 pièces — 64,00€',
    description: '24 macarons Pierre Morel',
    qty: '24 pièces',
    category: 'patisserie',
    img: '/creations-1.png',
    dietary: ['Sans gluten', 'Végétarien'],
  },
  {
    id: 'cookies',
    name: 'Cookie',
    shortName: 'Cookies',
    price: 17.90,
    label: '6 pièces — 17,90€',
    description: '6 cookies Laura Todd',
    qty: '6 pièces',
    category: 'patisserie',
    img: '/creations-2.png',
    dietary: ['Végétarien'],
  },
  {
    id: 'panna-cotta',
    name: 'Panna cotta fruits rouges',
    shortName: 'Panna cotta',
    price: 16.90,
    label: '6 pièces — 16,90€',
    description: '6 pièces',
    qty: '6 pièces',
    category: 'sucre-sale',
    img: '/creations-featured.webp',
    dietary: ['Sans gluten', 'Végétarien'],
  },
  {
    id: 'compote-pomme',
    name: 'Compote de pomme du verger',
    shortName: 'Compote pomme',
    price: 16.90,
    label: '6 pièces — 16,90€',
    description: '6 pièces',
    qty: '6 pièces',
    category: 'sucre-sale',
    img: '/creations-4.png',
    dietary: ['Vegan', 'Sans gluten'],
  },
]

export const getProductById = (id) => PRODUCTS.find(p => p.id === id)

// Couleurs des tags dietary
export const DIETARY_COLORS = {
  'Bio': { bg: 'rgba(74,124,74,0.1)', color: '#3a7c3a' },
  'Vegan': { bg: 'rgba(74,124,74,0.1)', color: '#3a7c3a' },
  'Sans gluten': { bg: 'rgba(224,161,38,0.12)', color: '#b07d10' },
  'Sans huile de palme': { bg: 'rgba(74,124,74,0.1)', color: '#3a7c3a' },
  'Végétarien': { bg: 'rgba(17,17,17,0.05)', color: 'rgba(17,17,17,0.45)' },
}
